name: reviewdog
on:
  pull_request:
  workflow_dispatch:

jobs:
  reviewdog:
    name: runner / vint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: vint
        uses: reviewdog/action-vint@v1
        with:
          github_token: ${{ secrets.github_token }}
